image: node:8.15.0

before_script:
  - node -v
  - npm install
  
cache:
  paths:
  - node_modules/
 
stages:
  - test
  - report

test_lambda:
  stage: test
  script:
   - npm run test-lambda

test_efsd:
  stage: test
  script:
   - npm run test-efsd
   
report_lambda:
  stage: report
  script:
   - npm run create-lambda-report
  artifacts:
    paths:
    - report/EFSD/index.html
    expire_in: 1 week